"""empty message

Revision ID: aa3c9df5bf8b
Revises: 6b690e3a61f7
Create Date: 2020-10-01 12:15:32.464109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3c9df5bf8b'
down_revision = '6b690e3a61f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_tags', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post_tags', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
