"""empty message

Revision ID: e1478dc14a60
Revises: aa3c9df5bf8b
Create Date: 2020-10-01 12:20:32.503068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1478dc14a60'
down_revision = 'aa3c9df5bf8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_tags', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'tags', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.alter_column('post_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post_tags', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
